### ISSUE TITLE
Model is not updated when i assign by others array

### ISSUE THREAD

**Issue by ChrisLHT** [teamcancode/ngx-form-control#3]
When i assigned an array to model for the first time , it worked so well . But when i assign another array to that model for the second time , it worked so weird . Please check and help me !!

**Comment by teamcancode** [comment]
Hi @ChrisLHT : I fixed in version 0.0.14, please recheck. Thanks alot 👍

**Comment by ChrisLHT** [comment]
It's working so well. So fast fixing & responding. Thank you so much for your assistance !
