### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by ChrisLHT** [teamcancode/ngx-form-control#6]
I would like to use Dynamic option creation in select2. Could you please insert another configuration (tag attribute) into your ngx-form-control? It would be more awesome. Thank you so much!

**Comment by teamcancode** [comment]
Hi @ChrisLHT : Thanks for your request!

I added "tags" & "tokenSeparators" options in version "0.0.19".
You can view the document of select2 here: https://github.com/teamcancode/ngx-form-control/blob/master/resources/doc/select2.md

**Comment by ChrisLHT** [comment]
Hi @teamcancode , it works so well right now. Thank you for your very detail documents
